spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e3mall?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # 默认开启了缓存，修改页面，则刷新的时候得不到修改后的页面，改为false
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.25.133
  application:
    name: search
  data:
    solr:
      host: http://192.168.25.133:8080/solr/collection1
  activemq:
    broker-url: tcp://192.168.25.133:61616

mybatis:
  type-aliases-package: com.chengyu.common.pojo
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
     count: countSql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8083

